insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (13, 'Fruit Salad Deluxe', 'Wine - Semi Dry Riesling Vineland', 26, 'Cabbage - Red', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (14, 'Pop - Club Soda Can', 'Oil - Peanut', 56, 'Rabbit - Whole', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (15, 'Pastry - Plain Baked Croissant', 'Muffin - Banana Nut Individual', 31, 'Nantucket Cranberry Juice', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (16, 'Olives - Morracan Dired', 'Gatorade - Orange', 46, 'Turkey - Whole, Fresh', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (17, 'Roe - Lump Fish, Red', 'Initation Crab Meat', 14, 'Temperature Recording Station', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (18, 'Foam Espresso Cup Plain White', 'Sandwich Wrap', 60, 'Butter Sweet', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (19, 'Compound - Pear', 'Ecolab - Solid Fusion', 58, 'Pasta - Orzo, Dry', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (20, 'Containter - 3oz Microwave Rect.', 'Cookies - Englishbay Wht', 10, 'Puff Pastry - Sheets', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (21, 'Salt - Kosher', 'Arrowroot', 50, 'Tortillas - Flour, 10', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (22, 'Cookie - Oreo 100x2', 'Beef - Ground Lean Fresh', 50, 'Salmon - Fillets', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (23, 'Stock - Veal, White', 'Beans - Long, Chinese', 55, 'Grouper - Fresh', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (24, 'Cinnamon Rolls', 'Compound - Pear', 69, 'Appetizer - Tarragon Chicken', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (25, 'Coriander - Ground', 'Tart Shells - Sweet, 4', 45, 'Lamb - Rack', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (26, 'Grand Marnier', 'Clam Nectar', 27, 'Soup - Campbells, Cream Of', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (27, 'Chambord Royal', 'Ham - Cooked', 24, 'Taro Leaves', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (28, 'Sugar - Monocystal / Rock', 'Wine - Red Oakridge Merlot', 73, 'Wheat - Soft Kernal Of Wheat', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (29, 'Rum - Cream, Amarula', 'Trout - Rainbow, Fresh', 20, 'Chinese Foods - Cantonese', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (30, 'Coffee - Almond Amaretto', 'Wine - Stoneliegh Sauvignon', 71, 'Peppercorns - Green', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (31, 'Truffle Cups Green', 'Tart - Butter Plain Squares', 59, 'Bagelers - Cinn / Brown', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (32, 'Russian Prince', 'Duck - Breast', 74, 'Pepper - Chili Powder', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (33, 'Chips - Doritos', 'Cakes Assorted', 12, 'Pepper - Black, Ground', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (34, 'Vinegar - Balsamic, White', 'Oil - Pumpkinseed', 47, 'Crab - Claws, 26 - 30', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (35, 'Vinegar - Champagne', 'Bouillion - Fish', 37, 'Lemonade - Kiwi, 591 Ml', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (36, 'Tea - Herbal Sweet Dreams', 'Wood Chips - Regular', 70, 'Cloves - Whole', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (37, 'Pineapple - Regular', 'Beef - Diced', 36, 'Butter Sweet', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (38, 'Spice - Greek 1 Step', 'Chicken Giblets', 34, 'Tart - Pecan Butter Squares', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (39, 'C - Plus, Orange', 'Trout - Rainbow, Frozen', 12, 'Kellogs All Bran Bars', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (40, 'Broom - Push', 'Prunes - Pitted', 53, 'Wine - White, Riesling, Semi - Dry', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (41, 'Cheese - Oka', 'Ice Cream Bar - Oreo Sandwich', 19, 'Wine - Alsace Gewurztraminer', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (42, 'Bananas', 'Bread - Dark Rye, Loaf', 50, 'Spinach - Spinach Leaf', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (43, 'Extract - Rum', 'Wine - Chardonnay South', 41, 'Pork - Bacon, Double Smoked', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (44, 'Yeast - Fresh, Fleischman', 'Marsala - Sperone, Fine, D.o.c.', 18, 'Mortadella', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (45, 'Swiss Chard', 'Compound - Raspberry', 17, 'Wine - Casillero Del Diablo', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (46, 'Soap - Mr.clean Floor Soap', 'Vodka - Moskovskaya', 42, 'Dikon', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (47, 'Wine - Dubouef Macon - Villages', 'Glass - Wine, Plastic, Clear 5 Oz', 59, 'Milk 2% 500 Ml', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (48, 'Sprouts - Peppercress', 'Tea - Decaf 1 Cup', 60, 'Spice - Montreal Steak Spice', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (49, 'Juice - Apple, 341 Ml', 'Whmis - Spray Bottle Trigger', 12, 'Wine - Gewurztraminer Pierre', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (50, 'Milk - 2%', 'Wine - White, Chardonnay', 10, 'Soup - Campbellschix Stew', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (51, 'Soy Protein', 'Pasta - Tortellini, Fresh', 31, 'Pork Loin Bine - In Frenched', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (52, 'Pie Box - Cello Window 2.5', 'Liqueur - Melon', 19, 'Mini - Vol Au Vents', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (53, 'Sugar Thermometer', 'Ham - Smoked, Bone - In', 49, 'Gherkin - Sour', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (54, 'Wine - Chardonnay South', 'Cleaner - Bleach', 48, 'Toamtoes 6x7 Select', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (55, 'Salmon - Sockeye Raw', 'Tomatoes - Vine Ripe, Yellow', 52, 'Pear - Asian', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (56, 'Petite Baguette', 'Kellogs All Bran Bars', 17, 'Sour Puss - Tangerine', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (57, 'Lemon Tarts', 'Sour Puss Raspberry', 55, 'Flour - So Mix Cake White', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (58, 'Beef - Kobe Striploin', 'Sauce - Vodka Blush', 33, 'Beef - Kindney, Whole', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (59, 'Berry Brulee', 'Tomatoes - Cherry, Yellow', 64, 'Mustard - Pommery', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (60, 'Table Cloth 53x69 White', 'Beets - Candy Cane, Organic', 72, 'Carbonated Water - Cherry', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (61, 'Muffin Puck Ww Carrot', 'Chicken - Whole Roasting', 51, 'Creme De Menth - White', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (62, 'Pimento - Canned', 'Beets - Golden', 61, 'Wine - Shiraz South Eastern', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (63, 'Nut - Hazelnut, Ground, Natural', 'Relish', 60, 'Appetizer - Smoked Salmon / Dill', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (64, 'Longos - Grilled Veg Sandwiches', 'C - Plus, Orange', 25, 'Icecream - Dibs', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (65, 'Tomatoes - Cherry, Yellow', 'Wine - White, Riesling, Semi - Dry', 64, 'Tomatoes Tear Drop Yellow', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (66, 'Sugar Thermometer', 'Cherries - Bing, Canned', 37, 'Tomatillo', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (67, 'Soup - Campbells Asian Noodle', 'Bread - White, Unsliced', 19, 'Sauce - Alfredo', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (68, 'Pork Loin Bine - In Frenched', 'V8 Splash Strawberry Kiwi', 11, 'Seedlings - Clamshell', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (69, 'Wine - Rioja Campo Viejo', 'Wine - Acient Coast Caberne', 66, 'Wine - Vineland Estate Semi - Dry', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (70, 'Durian Fruit', 'Food Colouring - Green', 48, 'Coffee - Decaffeinato Coffee', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (71, 'Beef - Striploin Aa', 'Cheese - St. Andre', 31, 'Wine - Clavet Saint Emilion', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (72, 'Wine - White, Lindemans Bin 95', 'Cocoa Feuilletine', 61, 'Salmon Steak - Cohoe 8 Oz', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (73, 'Pork - Bacon,back Peameal', 'Cup - Paper 10oz 92959', 70, 'Appetizer - Assorted Box', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (74, 'Lamb - Shoulder, Boneless', 'Rum - Cream, Amarula', 31, 'Veal - Sweetbread', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (75, 'Soup - Campbells - Chicken Noodle', 'Chicken - Thigh, Bone In', 29, 'Juice - Orangina', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (76, 'Wine - Alsace Gewurztraminer', 'Bananas', 30, 'Bag Clear 10 Lb', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (77, 'Soup Campbells Split Pea And Ham', 'Truffle Cups - Red', 10, 'Dooleys Toffee', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (78, 'Wine - Red, Cabernet Sauvignon', 'Melon - Watermelon Yellow', 11, 'Pork - Tenderloin, Frozen', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (79, 'Apple - Northern Spy', 'Foam Cup 6 Oz', 70, 'Pasta - Fusili, Dry', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (80, 'Chocolate - Feathers', 'Table Cloth 54x54 White', 43, 'Tomatoes', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (81, 'Molasses - Fancy', 'Flavouring Vanilla Artificial', 59, 'Cookie Dough - Double', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (82, 'Quail Eggs - Canned', 'Bagel - Ched Chs Presliced', 18, 'Wine - Acient Coast Caberne', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (83, 'Wine - Rosso Toscano Igt', 'Chicken - Breast, 5 - 7 Oz', 12, 'Pepper - Red Bell', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (84, 'Pork - Smoked Kassler', 'Haggis', 20, 'Chinese Foods - Thick Noodles', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (85, 'Pasta - Angel Hair', 'Rootbeer', 47, 'Oil - Olive Bertolli', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (86, 'Wine - Red, Concha Y Toro', 'Honey - Lavender', 50, 'Sauce - Fish 25 Ozf Bottle', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (87, 'Rabbit - Legs', 'Sauce - Demi Glace', 73, 'Wine - Red, Pelee Island Merlot', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (88, 'Juice - Orange, 341 Ml', 'Table Cloth 90x90 White', 69, 'Cheese Cloth No 60', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (89, 'Fork - Plastic', 'Pepper - Chili Powder', 51, 'Curry Paste - Green Masala', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (90, 'Water - Aquafina Vitamin', 'Wine - Prosecco Valdobienne', 38, 'Veal - Striploin', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (91, 'Sping Loaded Cup Dispenser', 'Soup - Campbells Beef Noodle', 25, 'Cup - 8oz Coffee Perforated', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (92, 'Pea - Snow', 'Oil - Avocado', 58, 'Passion Fruit', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (93, 'Longos - Chicken Wings', 'Coffee - Colombian, Portioned', 66, 'Green Scrubbie Pad H.duty', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (94, 'Mahi Mahi', 'Cheese - Ricotta', 15, 'Wine - Vidal Icewine Magnotta', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (95, 'Longos - Grilled Salmon With Bbq', 'Bread - Bistro Sour', 29, 'Mustard - Seed', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (96, 'Tea - Darjeeling, Azzura', 'Pork - Bacon, Sliced', 16, 'Cookie Dough - Oatmeal Rasin', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (97, 'Pork - Side Ribs', 'Caviar - Salmon', 28, 'Pork - Backfat', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (98, 'Huck Towels White', 'Nestea - Iced Tea', 15, 'Sugar - Crumb', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (99, 'Dish Towel', 'Longos - Burritos', 71, 'Island Oasis - Mango Daiquiri', 15);
insert into PRODUCT (id, TITLE, DESCRIPTION, PRICE, CATEGORY, MEDIA_ID) values (100, 'Energy - Boo - Koo', 'Wine - White, Riesling, Henry Of', 61, 'Truffle - Peelings', 15);
